# Generated by Django 5.2.15 on 2026-07-04 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('distribuidora', 'Distribuidora'), ('atacado', 'Atacado'), ('varejo_vizinho', 'Varejo vizinho')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('mercearia', 'Mercearia'), ('bebidas', 'Bebidas'), ('hortifruti', 'Hortifrúti'), ('limpeza', 'Limpeza')], max_length=20)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='código de barras (EAN)')),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo')], max_length=2)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('perecivel', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('observacao', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.fornecedor')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField(blank=True, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.produto')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('validade'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('motivo', models.CharField(choices=[('perda', 'Perda'), ('quebra', 'Quebra'), ('consumo', 'Consumo'), ('contagem', 'Ajuste de contagem')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='core.lote')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
