# Generated by Django 5.2.15 on 2026-07-05 00:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fornecedor_options_alter_ajuste_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão')], max_length=10)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_sem_lote', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Parte vendida sem cobertura de lote (estoque do sistema era menor que a prateleira). Discrepância a investigar.', max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='core.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='BaixaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='core.lote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='core.itemvenda')),
            ],
            options={
                'verbose_name': 'baixa de lote',
                'verbose_name_plural': 'baixas de lote',
            },
        ),
    ]
